name: pr-closed
description: Close pr-closed issues with no activity
resource: repository

configuration:
  resourceManagementConfiguration:
    scheduledSearches:
      - frequencies:
          - weekday:
              day: Monday
              time: 12:00
        filters:
          - isOpen
          - isIssue
          - hasLabel:
              label: pr-closed
          - noActivitySince:
              days: 60
        actions:
          - addReply:
              reply: Closing issue due to no activity in 60 days.
          - closeIssue

